### ISSUE TITLE
Improvement of Node

### ISSUE THREAD

**Issue by zwep** [gpilab/philips-data-reader#11]
Hi,

I would like to be able to call lthe `ReadPhillips` Node with a string (file path) as input, in addition to the file browser.
Can this be made possible? Or is there a way for me to extend this Node somehow? 
I can imagine that by inherriting the class, adding via another `__init__` statement an additional input port, and overwriting the file name that is gained by the file browser, I should be able to fix this.

**Comment by aganders3** [comment]
If you right click on the file browser widget in the node menu you can create a "widget port" for the node. From there you can feed a string into the node for the file path. Is this what you mean?

**Comment by zwep** [comment]
Hi, yeah I think that is it.. Im quite new to this GPI framework, so Im not fully knowledgeable on what is possible. 
Thanks for the replies btw!
