### ISSUE TITLE
GPI v1.0.2 + ReadPhilips release 6

### ISSUE THREAD

**Issue by anguszlau** [gpilab/philips-data-reader#6]
Hi there,

I'm trying to load some R5.3 .raw/.lab/.sin radial data with the ReadPhilips node. It's 2D radial data.
The node appears to load correctly but when I click the read button I get the error

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alau/gpi_stack/lib/python3.5/site-packages/gpi/functor.py", line 367, in run
    self._proxy.append(['retcode', self._func()])
  File "/home/ash/gpi/philips/fileIO/GPI/ReadPhilips_GPI.py", line 506, in compute
  File "readPhilipsExports.py", line 1370, in readRaw
  File "readMira.py", line 108, in decodeMira
  File "readMira.py", line 23, in getShort
NameError: name 'file' is not defined

gpi.node:601 - ERROR - ReadPhilips: compute() failed.
```

This is using a local install with GPI_Install_Latest.sh to ~/gpi_stack, and ReadPhilips_Linux_2016-04-11.zip unzipped to ~/gpi/philips. I also get the same error message using the provided VM.

Am I missing something obvious? I can read the data using the older version on the paradise community site (+python 2)... but it's not compatible with the python 3 GPI version.

Thanks

**Comment by aganders3** [comment]
Thanks for the report, @anguszlau. Unfortunately we are pretty short-staffed for this project, but I'll forward this on to the person who wrote the code for this and hopefully he can help sort it out.

**Comment by rkrobison** [comment]
Thank you for the feedback @anguszlau. We have posted a new release of ReadPhilips (https://github.com/gpilab/philips-data-reader/releases/tag/v1.0.2) which should correct the issue you are facing. Please note that this new release encompasses nearly a year of changes to ReadPhilips. Please feel free to post any additional issues you encounter.

**Comment by anguszlau** [comment]
Thanks for the response, @aganders3 and @rkrobison!
